version: "3.8"

services:

  aumsu_postgres:
    restart: unless-stopped
    image: postgres:9.5-alpine
    container_name: aumsu_postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
