version: "3.8"

services:

  aumsu_postgres:
    restart: unless-stopped
    image: postgres:9.5-alpine
    container_name: aumsu_postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network

  go_application:
    restart: unless-stopped
    build: "."
    container_name: aumsu_backend
    depends_on:
      - aumsu_postgres
    expose:
      - 8010
    volumes:
      - "images:/var/www/images"
    environment:
      MODE: production
    networks:
      - app_network
      - server

volumes:
  postgres-data:
  images:

networks:
  app_network:
    driver: bridge
  server:
    external: true
